In [2]:
import pandas as pd

df = pd.read_csv('banking.csv')

In [3]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [4]:
df['job'] = df['job'].map({'blue-collar':0, 'technician':1, 'management':2, 'services':3,'retired':4, 'admin.':5, 'housemaid':6, 'unemployed':7, 'entrepreneur':8, 'self-employed':9, 'unknown':10, 'student':11}).astype(int) 
df['marital'] = df['marital'].map({'married':0, 'single':1, 'divorced':2, 'unknown':3}).astype(int)
df['education'] = df['education'].map({'basic.4y':0, 'unknown':1, 'university.degree':2, 'high.school':3, 'basic.9y':4,'professional.course':5, 'basic.6y':6, 'illiterate':7}).astype(int)
df['default'] = df['default'].map({'unknown':0, 'no':1, 'yes':2}).astype(int)
df['housing'] = df['housing'].map({'unknown':0, 'no':1, 'yes':2}).astype(int)
df['loan'] = df['loan'].map({'unknown':0, 'no':1, 'yes':2}).astype(int)
df['contact'] = df['contact'].map({'cellular':0, 'telephone':1}).astype(int)
df['month'] = df['month'].map({'aug':0, 'nov':1, 'jun':2, 'apr':3, 'jul':4, 'may':5, 'oct':6, 'mar':7, 'sep':8,
       'dec':9,'feb':10,'apr':11}).astype(int)
df['day_of_week'] = df['day_of_week'].map({'thu':3, 'fri':4,'sat':5, 'sun':6, 'tue':1, 'mon':0, 'wed':2}).astype(int)
df['poutcome'] = df['poutcome'].map({'nonexistent':0, 'success':1, 'failure':2}).astype(int)

In [8]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,44,0,0,0,0,2,1,0,0,3,...,1,999,0,0,1.4,93.444,-36.1,4.963,5228.1,0
1,53,1,0,1,1,1,1,0,1,4,...,1,999,0,0,-0.1,93.200,-42.0,4.021,5195.8,0
2,28,2,1,2,1,2,1,0,2,3,...,3,6,2,1,-1.7,94.055,-39.8,0.729,4991.6,1
3,39,3,0,3,1,1,1,0,11,4,...,2,999,0,0,-1.8,93.075,-47.1,1.405,5099.1,0
4,55,4,0,0,1,2,1,0,0,4,...,1,3,1,1,-2.9,92.201,-31.4,0.869,5076.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,59,4,0,3,0,1,2,1,2,3,...,1,999,0,0,1.4,94.465,-41.8,4.866,5228.1,0
41184,31,6,0,0,0,1,1,1,5,3,...,2,999,0,0,1.1,93.994,-36.4,4.860,5191.0,0
41185,42,5,1,2,0,2,2,1,5,2,...,3,999,0,0,1.1,93.994,-36.4,4.857,5191.0,0
41186,48,1,0,5,1,1,2,1,6,1,...,2,999,0,0,-3.4,92.431,-26.9,0.742,5017.5,0
41187,25,11,1,3,1,1,1,1,5,4,...,4,999,0,0,1.1,93.994,-36.4,4.859,5191.0,0

In [5]:
df['campaign'].unique()
df['previous'].unique()

array([0, 2, 1, 3, 4, 5, 7, 6], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix

y = df['y']
X = df.drop('y', axis =1)


x_train_orginal, x_test_orginal, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.2)
scaler = MinMaxScaler()

x_train = scaler.fit_transform(x_train_orginal)
x_test = scaler.fit_transform(x_test_orginal)

In [7]:
x_test

array([[0.17333333, 0.81818182, 0.33333333, ..., 0.60251046, 0.96792669,
        0.85973535],
       [0.49333333, 0.36363636, 0.        , ..., 0.33891213, 0.99106529,
        1.        ],
       [0.33333333, 0.27272727, 0.66666667, ..., 0.60251046, 0.96792669,
        0.85973535],
       ...,
       [0.44      , 0.        , 0.        , ..., 0.61506276, 0.99221077,
        1.        ],
       [0.94666667, 0.36363636, 0.66666667, ..., 0.0334728 , 0.23550974,
        0.51228733],
       [0.49333333, 0.45454545, 0.        , ..., 0.86610879, 0.0185567 ,
        0.20378072]])

# LogisticRegression

In [6]:
from sklearn.linear_model import LogisticRegression


model = LogisticRegression(max_iter=300,n_jobs=-1) 

#TRAINING THE MODEL
model.fit(x_train,y_train)

#TESTING THE MODEL
confidence = model.score(x_test,y_test)


print(confidence)

0.896698227725176

# SVC - LINEAR

In [7]:
from sklearn.svm import SVC

svc_linear = SVC(kernel = 'linear', C = 10, gamma = 0.1)
svc_linear.fit(x_train, y_train)

confidence = svc_linear.score(x_test,y_test)


print(confidence)

0.9021607186210245

# SVC - Rbf

In [8]:
from sklearn.svm import SVC

svc_linear = SVC(kernel = 'rbf', C = 100, gamma = 0.1)
svc_linear.fit(x_train, y_train)

confidence = svc_linear.score(x_test,y_test)


print(confidence)

0.9041029376062151

# Saving Model

In [10]:
import pickle

with open('./Marketing_campaign.pkl', 'wb') as f:
    pickle.dump(svc_linear, f)

# Loading model

In [11]:
import pickle

with open('./Marketing_campaign.pkl', 'rb') as f:
    loaded_svc_linear = pickle.load(f)

In [12]:
confidence = loaded_svc_linear.score(x_test,y_test)

In [13]:
print(confidence)

0.9041029376062151

# SVC - Poly

In [14]:
from sklearn.svm import SVC

svc_linear = SVC(kernel = 'poly', C = 10, gamma = 0.1)
svc_linear.fit(x_train, y_train)

confidence = svc_linear.score(x_test,y_test)


print(confidence)

0.9020393299344501

# Bagging

In [18]:
from sklearn.ensemble import BaggingClassifier
bag_clf = BaggingClassifier(log_clf, n_estimators=500, max_samples=100, bootstrap=False, random_state=42)
bag_clf.fit(x_train, y_train)

confidence = bag_clf.score(x_test,y_test)


print(confidence)

0.8856518572469045

In [17]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression


log_clf = LogisticRegression() 

bag_clf = BaggingClassifier(log_clf, n_estimators=500, max_samples=100, bootstrap=True, random_state=42, oob_score = True)
bag_clf.fit(x_train, y_train)

confidence = bag_clf.score(x_test,y_test)


print(confidence)

0.8856518572469045

# DecisionTreeClassifier

In [19]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier() 

#TRAINING THE MODEL
model.fit(x_train,y_train)

#TESTING THE MODEL
confidence = model.score(x_test,y_test)


print(confidence)

0.8362466618111192

# KNeighborsClassifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=20) 

#TRAINING THE MODEL
model.fit(x_train,y_train)

#TESTING THE MODEL
confidence = model.score(x_test,y_test)


print(confidence)

0.8970623937848993

# GUI

In [43]:
import pickle
import pandas as pd

with open('./Marketing_campaign.pkl', 'rb') as f:
    loaded_svc_linear = pickle.load(f)


import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
# Creating tkinter window
window = tk.Tk()


#window.geometry('1000x1000')

window.title('Marketing_campaign')



#Column 1 
age = ttk.Label(window, text = "age :", font = ("Times New Roman", 10)).grid(column = 0,  row = 0, padx = 10, pady = 25)
age_var=tk.StringVar()
age_entrybox=ttk.Entry(window,width=27,textvariable=age_var)
age_entrybox.grid(row=0,column=1)

#Column 2
job = ttk.Label(window, text = "Select the Job :", font = ("Times New Roman", 10)).grid(column = 0,  row = 1, padx = 10, pady = 25)
job_var = tk.StringVar()
job_choosen = ttk.Combobox(window, width = 27, textvariable = job_var)
job_choosen['values'] = ('blue-collar', 'technician', 'management', 'services','retired', 'admin.', 'housemaid', 'unemployed', 'entrepreneur', 'self-employed', 'unknown', 'student')
job_choosen.grid(column = 1, row = 1)
job_choosen.current(1) 


#Column 3
marital = ttk.Label(window, text = "Select the marital :", font = ("Times New Roman", 10)).grid(column = 0,  row = 2, padx = 10, pady = 25)
marital_var = tk.StringVar()
marital_choosen = ttk.Combobox(window, width = 27, textvariable = marital_var)
marital_choosen['values'] = ('married', 'single', 'divorced', 'unknown')
marital_choosen.grid(column = 1, row = 2)
marital_choosen.current(1)



#Column 4
education = ttk.Label(window, text = "Select the education :", font = ("Times New Roman", 10)).grid(column = 0,  row = 3, padx = 10, pady = 25)
education_var = tk.StringVar()
education_choosen = ttk.Combobox(window, width = 27, textvariable = education_var)
education_choosen['values'] = ('basic.4y', 'unknown', 'university.degree', 'high.school', 'basic.9y','professional.course', 'basic.6y', 'illiterate')
education_choosen.grid(column = 1, row = 3)
education_choosen.current(1)


#Column 5
default = ttk.Label(window, text = "Select the default :", font = ("Times New Roman", 10)).grid(column = 0,  row = 4, padx = 10, pady = 25)
default_var = tk.StringVar()
default_choosen = ttk.Combobox(window, width = 27, textvariable = default_var)
default_choosen['values'] = ('unknown', 'no', 'yes')
default_choosen.grid(column = 1, row = 4)
default_choosen.current(1)


#Column 6
housing = ttk.Label(window, text = "Select the housing :", font = ("Times New Roman", 10)).grid(column = 0,  row = 5, padx = 10, pady = 25)
housing_var = tk.StringVar()
housing_choosen = ttk.Combobox(window, width = 27, textvariable = housing_var)
housing_choosen['values'] = ('unknown', 'no', 'yes')
housing_choosen.grid(column = 1, row = 5)
housing_choosen.current(1)


#Column 7
loan = ttk.Label(window, text = "Select the loan_satus :", font = ("Times New Roman", 10)).grid(column = 0,  row = 6, padx = 10, pady = 25)
loan_var = tk.StringVar()
loan_choosen = ttk.Combobox(window, width = 27, textvariable = loan_var)
loan_choosen['values'] = ('unknown', 'no', 'yes')
loan_choosen.grid(column = 1, row = 6)
loan_choosen.current(1)

#Column 8
contact = ttk.Label(window, text = "Select the contact :", font = ("Times New Roman", 10)).grid(column = 0,  row = 7, padx = 10, pady = 25)
contact_var = tk.StringVar()
contact_choosen = ttk.Combobox(window, width = 27, textvariable = contact_var)
contact_choosen['values'] = ('cellular', 'telephone')
contact_choosen.grid(column = 1, row = 7)
contact_choosen.current(1)

#Column 9
month = ttk.Label(window, text = "Select the month :", font = ("Times New Roman", 10)).grid(column = 0,  row = 8, padx = 10, pady = 25)
month_var = tk.StringVar()
month_choosen = ttk.Combobox(window, width = 27, textvariable = month_var)
month_choosen['values'] = ('aug', 'nov', 'jun', 'apr', 'jul', 'may', 'oct', 'mar', 'sep', 'dec','feb','jan')
month_choosen.grid(column = 1, row = 8)
month_choosen.current(1)

#Column 10
day_of_week = ttk.Label(window, text = "Select the day :", font = ("Times New Roman", 10)).grid(column = 0,  row = 9, padx = 10, pady = 25)
day_of_week_var = tk.StringVar()
day_of_week_choosen = ttk.Combobox(window, width = 27, textvariable = day_of_week_var)
day_of_week_choosen['values'] = ('thu', 'fri','sat', 'sun', 'tue', 'mon', 'wed')
day_of_week_choosen.grid(column = 1, row = 9)
day_of_week_choosen.current(1)


#Column 11
poutcome = ttk.Label(window, text = "Select the poutcome :", font = ("Times New Roman", 10)).grid(column = 10,  row = 0, padx = 10, pady = 25)
poutcome_var = tk.StringVar()
poutcome_choosen = ttk.Combobox(window, width = 27, textvariable = poutcome_var)
poutcome_choosen['values'] = ('nonexistent', 'success', 'failure')
poutcome_choosen.grid(column = 11, row = 0)
poutcome_choosen.current(1)


#Column 12
emp_var_rate = ttk.Label(window, text = "emp_var_rate :", font = ("Times New Roman", 10)).grid(column = 10,  row = 1, padx = 10, pady = 25)
emp_var_rate_var=tk.StringVar()
emp_var_rate_entrybox=ttk.Entry(window,width=27,textvariable=emp_var_rate_var)
emp_var_rate_entrybox.grid(row=1,column=11)

#Column 13
duration = ttk.Label(window, text = "Duration :", font = ("Times New Roman", 10)).grid(column = 10,  row = 2, padx = 10, pady = 25)
duration_var=tk.StringVar()
duration_entrybox=ttk.Entry(window,width=27,textvariable=duration_var)
duration_entrybox.grid(row=2,column=11)

#Column 14
campaign = ttk.Label(window, text = "Campaign :", font = ("Times New Roman", 10)).grid(column = 10,  row = 3, padx = 10, pady = 25)
campaign_var=tk.StringVar()
campaign_choosen = ttk.Combobox(window, width = 27, textvariable = campaign_var)
campaign_choosen['values'] = (1,  3,  2,  8,  5,  4, 25, 11, 12, 18,  6, 17,  7, 20, 16, 14, 10,
        9, 19, 29, 13, 40, 15, 34, 22, 24, 41, 21, 23, 39, 28, 27, 31, 35,
    26, 30, 32, 43, 33, 42, 56, 37)
#campaign_entrybox=ttk.Entry(window,width=27,textvariable=campaign_var)
campaign_choosen.grid(row=3,column=11)
campaign_choosen.current(1)

#Column 15
pdays = ttk.Label(window, text = "Pdays :", font = ("Times New Roman", 10)).grid(column = 10,  row = 4, padx = 10, pady = 25)
pdays_var=tk.StringVar()
pdays_entrybox=ttk.Entry(window,width=27,textvariable=pdays_var)
pdays_entrybox.grid(row=4,column=11)

#Column 16
previous = ttk.Label(window, text = "Previous :", font = ("Times New Roman", 10)).grid(column = 10,  row = 5, padx = 10, pady = 25)
previous_var=tk.StringVar()
previous_choosen = ttk.Combobox(window, width = 27, textvariable = previous_var)
previous_choosen['values'] = (0, 2, 1, 3, 4, 5, 7, 6)
previous_choosen.grid(column = 11, row = 5)
previous_choosen.current(1)
#previous_entrybox=ttk.Entry(window,width=27,textvariable=previous_var)
#previous_entrybox.grid(row=5,column=11)

#Column 17
cons_price_idx = ttk.Label(window, text = "Cons_price_idx :", font = ("Times New Roman", 10)).grid(column = 10,  row = 6, padx = 10, pady = 25)
cons_price_idx_var=tk.StringVar()
cons_price_idx_entrybox=ttk.Entry(window,width=27,textvariable=cons_price_idx_var)
cons_price_idx_entrybox.grid(row=6,column=11)

#Column 18
cons_conf_idx = ttk.Label(window, text = "Cons_conf_idx :", font = ("Times New Roman", 10)).grid(column = 10,  row = 7, padx = 10, pady = 25)
cons_conf_idx_var=tk.StringVar()
cons_conf_idx_entrybox=ttk.Entry(window,width=27,textvariable=cons_conf_idx_var)
cons_conf_idx_entrybox.grid(row=7,column=11)

#Column 19
euribor3m = ttk.Label(window, text = "Euriborem :", font = ("Times New Roman", 10)).grid(column = 10,  row = 8, padx = 10, pady = 25)
euribor3m_var=tk.StringVar()
euribor3m_entrybox=ttk.Entry(window,width=27,textvariable=euribor3m_var)
euribor3m_entrybox.grid(row=8,column=11)

#Column 20
nr_employed = ttk.Label(window, text = "nr_employed :", font = ("Times New Roman", 10)).grid(column = 10,  row = 9, padx = 10, pady = 25)
nr_employed_var=tk.StringVar()
nr_employed_entrybox=ttk.Entry(window,width=27,textvariable=nr_employed_var)
nr_employed_entrybox.grid(row=9,column=11)




import pandas as pd
DF = pd.DataFrame()

global DB
import pandas as pd
DF = pd.DataFrame(columns=['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed'])
def action():   
    AGE=age_var.get()
    DF.loc[0,'age']=AGE
    JOB=job_var.get()
    DF.loc[0,'job']=JOB
    MARITAL=marital_var.get()
    DF.loc[0,'marital']=MARITAL
    EDUCATION=education_var.get()
    DF.loc[0,'education']=EDUCATION
    DEFAULT=default_var.get()
    DF.loc[0,'default']=DEFAULT
    HOUSING=housing_var.get()
    DF.loc[0,'housing']=HOUSING
    LOAN=loan_var.get()
    DF.loc[0,'loan']=LOAN
    CONTACT=contact_var.get()
    DF.loc[0,'contact']=CONTACT
    
    MONTH=month_var.get()
    DF.loc[0,'month']=MONTH
    Day_Of_Week=day_of_week_var.get()
    DF.loc[0,'day_of_week']=Day_Of_Week
    DURATION=duration_var.get()
    DF.loc[0,'duration']=DURATION
    CAMPAIGN=campaign_var.get()
    DF.loc[0,'campaign']=CAMPAIGN
    PDAYS=pdays_var.get()
    DF.loc[0,'pdays']=PDAYS
    PREVIOUS=previous_var.get()
    DF.loc[0,'previous']=PREVIOUS
    POUT=poutcome_var.get()
    DF.loc[0,'poutcome']=POUT
    EMP_VAR=emp_var_rate_var.get()
    DF.loc[0,'emp_var_rate']=EMP_VAR
    
    CON_PRICE= cons_price_idx_var.get()
    DF.loc[0,'cons_price_idx']=CON_PRICE
    CONS=cons_conf_idx_var.get()
    DF.loc[0,'cons_conf_idx']=CONS
    EURI=euribor3m_var.get()
    DF.loc[0,'euribor3m']=EURI
    EMPLOY=nr_employed_var.get()
    DF.loc[0,'nr_employed']=EMPLOY
    
DB=DF

def filedreq():
    if age_var.get() == "":
        print("Age Field is Empty!!")
        user = "Age input is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=11,column=1)


    elif duration_var.get() == "":
        print("duration Field is Empty!!")
        user = "duration Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    
    elif pdays_var.get() == "":
        print("pdays Field is Empty!!")
        user = "pdays Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    
    elif emp_var_rate_var.get() == "":
        print("emp_var_rate Field is Empty!!")
        user = "emp_var_rate Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    elif cons_price_idx_var.get() == "":
        print("cons_price_idx Field is Empty!!")
        user = "cons_price_idx Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    elif cons_conf_idx_var.get() == "":
        print("cons_conf_idx Field is Empty!!")
        user = "cons_conf_idx Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    elif euribor3m_var.get() == "":
        print("euriborem Field is Empty!!")
        user = "euriborem Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    elif nr_employed_var.get() == "":
        print("nr_employed Field is Empty!!")
        user = "nr_employed Field is Empty!!"
        ttk.Label(window, text=user, font = ("Times New Roman", 10)).grid(row=12,column=1)
    else:
        pass

def Output():
    action()
    filedreq()
    DB["age"] = pd.to_numeric(DB["age"])
    DB["duration"] = pd.to_numeric(DB["duration"])
    DB["campaign"] = pd.to_numeric(DB["campaign"])
    DB["pdays"] = pd.to_numeric(DB["pdays"])
    DB["previous"] = pd.to_numeric(DB["previous"])
    DB["emp_var_rate"] = pd.to_numeric(DB["emp_var_rate"])
    DB["cons_price_idx"] = pd.to_numeric(DB["cons_price_idx"])
    DB["cons_conf_idx"] = pd.to_numeric(DB["cons_conf_idx"])
    DB["euribor3m"] = pd.to_numeric(DB["euribor3m"])
    DB["nr_employed"] = pd.to_numeric(DB["nr_employed"])
    DB['job'] = DB['job'].map({'blue-collar':0, 'technician':1, 'management':2, 'services':3,'retired':4, 'admin.':5, 'housemaid':6, 'unemployed':7, 'entrepreneur':8, 'self-employed':9, 'unknown':10, 'student':11}).astype(int) 
    DB['marital'] = DB['marital'].map({'married':0, 'single':1, 'divorced':2, 'unknown':3}).astype(int)
    DB['education'] = DB['education'].map({'basic.4y':0, 'unknown':1, 'university.degree':2, 'high.school':3, 'basic.9y':4,'professional.course':5, 'basic.6y':6, 'illiterate':7}).astype(int)
    DB['default'] = DB['default'].map({'unknown':0, 'no':1, 'yes':2}).astype(int)
    DB['housing'] = DB['housing'].map({'unknown':0, 'no':1, 'yes':2}).astype(int)
    DB['loan'] = DB['loan'].map({'unknown':0, 'no':1, 'yes':2}).astype(int)
    DB['contact'] = DB['contact'].map({'cellular':0, 'telephone':1}).astype(int)
    DB['month'] = DB['month'].map({'aug':0, 'nov':1, 'jun':2, 'apr':3, 'jul':4, 'may':5, 'oct':6, 'mar':7, 'sep':8,
           'dec':9,'feb':10,'jan':11}).astype(int)
    DB['day_of_week'] = DB['day_of_week'].map({'thu':3, 'fri':4,'sat':5, 'sun':6, 'tue':1, 'mon':0, 'wed':2}).astype(int)
    DB['poutcome'] = DB['poutcome'].map({'nonexistent':0, 'success':1, 'failure':2}).astype(int)

    db = scaler.transform(DB)


    output=loaded_svc_linear.predict(db)
    print(output)
    if output == 1:

        MsgBox = messagebox.showinfo("Marketing_campaign results", 'Campaign got positive response')
        print("achived")
    else:
        MsgBox = messagebox.showinfo('Marketing_campaign results', 'Campaign got no response')
        print("not achived")

def reset():
    nr_employed_var.set("")
    age_var.set("")
    duration_var.set("")
    pdays_var.set("")
    emp_var_rate_var.set("")
    cons_conf_idx_var.set("")
    euribor3m_var.set("")
    
 

    
Predict_button=ttk.Button(window,text="Predict",command=Output,width=25)
Predict_button.grid(row=10,column=15)

reset_button=ttk.Button(window,text="Reset",command=reset,width=25)
reset_button.grid(row=10,column=11)


window.mainloop()

[0]
not achived
[1]
achived

In [13]:
output_list = []
df = pd.DataFrame(columns=["1","2","3"])
df.loc[0,:] = output_list

In [14]:
df

   1  2  3
0  1  2  3

In [15]:
x_test = scaler.fit_transform(df)

In [ ]:
with open('Marketing_campaign.pkl', 'rb') as f:
            loaded_svc_linear = pickle.load(f)
        
output=loaded_svc_linear.predict(db)

print(output)
if output == 1:
    print("achieved")
else:
    print("not achieved")